# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 1

[launcher]
author = Splunk
version = 1.0.0

[ui]
is_visible = 0
label = app1
docs_section_override = AddOns:released

[package]
id = Splunk_TA_app1

[triggers]
reload.addon_builder = simple
reload.splunk_ta_app1_account = simple
reload.splunk_ta_app1_settings = simple
reload.passwords = simple
reload.logging = logging.conf

