target:
  url: https://staging.admin.splunk.com/scv-shw-d3af438c5ac0c7/adminconfig/v2/apps/victoria
apps:
  Splunk_TA_app1:
    s3-bucket: splunk-apps-deployment
    source: apps/Splunk_TA_app1.tgz
    config:
      - ./Splunk_TA_app1/*.conf
  buttercup_app_for_splunk:
    s3-bucket: splunk-apps-deployment
    source: apps/buttercup_app_for_splunk.tgz
    config:
      - ./buttercup_app_for_splunk/*.conf
splunkbase-apps:
  # Splunkbase apps
  CB Protection App for Splunk:
    version: 2.0
    app_id: 1790
    licence: https://cdn.splunkbase.splunk.com/static/misc/eula.html
  TA for Cisco IOS:
    version: 2.7.5
    app_id: 1467
    licence: https://creativecommons.org/licenses/by-nc-sa/4.0