target:
  url: https://staging.admin.splunk.com/scv-shw-124c06f337f0a4/adminconfig/v2/apps/victoria
apps:
  leaflet_maps_app_custom:
    source: philips-ci-test
    directory: apps/leaflet_maps_app_custom.spl
    config:
      - ./app1/*.conf
  redfish-add-on-for-splunk_107:
    source: philips-ci-test
    directory: apps/redfish-add-on-for-splunk_107.tgz
    config:
      - ./app1/*.conf
