target:
  url: https://staging.admin.splunk.com/scv-shw-77b8de5e8af3f1/adminconfig/v2/apps/victoria
  stack: scv-shw-77b8de5e8af3f1
apps:
  Splunk_TA_app1:
    source: philips-ci-test
    directory: apps/Splunk_TA_app1.tgz
    config:
      - ./app1/*.conf
splunkbase-apps:
  # Splunkbase apps
  Tenable Add-On for Splunk:
    version: 7.0.0
    app_id: 4060
  Splunk Add on for Microsoft Azure:
    version: 4.2.0
    app_id: 3757
