target:
  url: https://staging.admin.splunk.com/scv-shw-d037e758abafa2/adminconfig/v2/apps/victoria
apps:
  Splunk_TA_app1:
    s3-bucket: philips-ci-test
    source: apps/Splunk_TA_app1.tgz
    config:
      - ./app1/*.conf
splunkbase-apps:
  TA-tenable:
    version: 7.0.0
    app_id: 4060
    licence: https://cdn.splunkbase.splunk.com/static/misc/eula.html
  TA-MS-AAD:
    version: 4.2.0
    app_id: 3757
    licence: https://www.splunk.com/en_us/legal/splunk-general-terms.html
