target:
  url: https://staging.admin.splunk.com/scv-shw-d037e758abafa2
apps:
  Splunk_TA_app1:
    s3-bucket: splunk-apps-deployment
    source: apps/Splunk_TA_app1.tgz
    config:
      - ./Splunk_TA_app1/*.conf
splunkbase-apps:
  TA for Tebable:
    version: 7.0.0
  TA for MS Azure:
    version: 4.2.0
