#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = 1
label = Buttercup App for Splunk

[launcher]
author = FDSE
description = Giddy up!
version = 1.0.0

[triggers]
reload.logging = logging.conf
reload.passwords = simple
reload.buttercup_app_for_splunk = simple

