[monitor://$SPLUNK_HOME/etc/apps/buttercup_app_for_splunk/samples/w3c_example.log]
disabled = true
sourcetype = buttercup:w3c
# sourcetype = buttercup:w3c:example
index = buttercup

[monitor:///Users/jwelsh/*]
disabled = true
sourcetype = buttercup:w3c
# sourcetype = buttercup:w3c:example
index = buttercup