[buttercup:w3c]
SHOULD_LINEMERGE = false
# ------------------------------
# For date & time variables please refer to:
# https://docs.splunk.com/Documentation/Splunk/7.3.1/SearchReference/Commontimeformatvariables
# ------------------------------
TIME_PREFIX = ^
MAX_TIMESTAMP_LOOKAHEAD = 19
TIME_FORMAT = %Y-%m-%d %H:%M:%S
KV_MODE = none
REPORT-extractfields = extractfields
#EXTRACT-fieldextractions = ^(?P<eventdate>[^\s]*)\s(?P<eventtime>[^\s]*)\s(?P<cs_method>[^\s]*)\s(?P<cs_uri_stem>[^\s]*)\s(?P<cs_uri_query>[^\s]*)\s(?P<s_port>[^\s]*)\s(?P<cs_username>[^\s]*)\s(?P<c_ip>[^\s]*)\s(?P<cs_version>[^\s]*)\s(?P<cs_User_Agent>[^\s]*)\s(?P<cs_Cookie>[^\s]*)\s(?P<cs_Referer>[^\s]*)\s(?P<cs_host>[^\s]*)\s(?P<sc_status>[^\s]*)\s(?P<sc_substatus>[^\s]*)\s(?P<sc_win32_status>[^\s]*)\s(?P<sc_bytes>[^\s]*)\s(?P<cs_bytes>[^\s]*)\s(?P<time_taken>[^\s]*)
