on:
  pull_request:
    types:
      - closed
    branches:
      - main
    path:
      - environments/*/**

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ["uat/ses", "uat/es", "prod/es", "prod/ses"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyyaml
          pip install boto3
      - name: Deploy to ${{ matrix.environment }}
        env:
          # In case of authentication needed to access target server
          SERVER_KEY: ${{ secrets.KEY_${{ matrix.environment | upper }} }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SPLUNK_USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
        run: |
          python deploy.py --env ${{ matrix.environment }}
          echo "Deploying to ${{ matrix.environment }} environment"
      - name: Upload deployment report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-output
          path: artifacts/
