name: Manually Deploy Splunk Apps

on:
  workflow_dispatch:
jobs:
  download-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - name: "uat/ses"
            token_key: "SPLUNK_TOKEN_UAT_SES"
          - name: "uat/es"
            token_key: "SPLUNK_TOKEN_UAT_ES"
          - name: "prod/es"
            token_key: "SPLUNK_TOKEN_PROD_ES"
          - name: "prod/ses"
            token_key: "SPLUNK_TOKEN_PROD_SES"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pyyaml
          pip install boto3
          pip install requests
      - name: Deploy to ${{ matrix.environment.name }}
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SPLUNK_USERNAME: ${{ secrets.SPLUNK_USERNAME }}
          SPLUNK_PASSWORD: ${{ secrets.SPLUNK_PASSWORD }}
          SPLUNK_TOKEN: ${{ secrets[matrix.environment.token_key] }}
        run: |
          echo "Deploying to ${{ matrix.environment.name }} environment"
          python -u deploy.py ${{ matrix.environment.name }}
      - name: Upload deployment report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: deployment-report
          path: artifacts/
      - name: Prepare sanitized artifact name
        id: sanitize
        run: echo "SANITIZED_NAME=${{ matrix.environment.name }}" | sed 's/[\/:*?"<>|]/-/g' >> $GITHUB_ENV
      - name: Debugging apps re-package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SANITIZED_NAME }}-tgz-files
          path: ./*.tgz

