name: Package Private Apps (Tar)

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    path:
      - apps/*/**

jobs:
  package-and-upload:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-cli@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Package Splunk App
        run: |
          ROOT=$(pwd)
          # Find the first-level directory with changes
          CHANGED_FOLDER=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -oE '^apps/[^/]+' | sort -u | head -n 1)
          if [ -z "$CHANGED_FOLDER" ]; then
            echo "No changes detected in app folders. Exiting."
            exit 1
          fi
          echo "Changed folder: $CHANGED_FOLDER"
          mkdir -p $ROOT/dist
          # Packaging all changed apps
          for ch in $CHANGED_FOLDER
          do
            version=$(cat $ch/app.manifest | jq -r '.info.id.name')
            tar -czf $ROOT/dist/$ch_$version.tar.gz ./$ch
          done
      - name: Upload to S3
        run: |
          aws s3 sync ./dist/*.tgz s3://your-s3-bucket-name/apps/
