name: Package Private Apps (Tar)

on: workflow_call

jobs:
  package-and-upload:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ["uat/ses", "uat/es", "prod/es", "prod/ses"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Package Splunk App
        run: |
          # Base directory to search
          BASE_DIR="apps"

          # Check if the base directory exists, then list its subdirectories
          if [ -d "$BASE_DIR" ]; then
            SUBFOLDERS=$(find "$BASE_DIR" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort -u)
          else
            SUBFOLDERS=""
          fi

          # Print the result for debugging
          echo "Subfolders for environment $BASE_DIR:"
          echo "$SUBFOLDERS"

          # Save the result as an environment variable for use in later steps
          echo "Changed folder: $SUBFOLDERS"
          # Packaging all changed apps
          for ch in $SUBFOLDERS
          do
            sudo mkdir -p dist/
            pip install splunk-add-on-ucc-framework
            pip install splunk-packaging-toolkit
            ucc-gen build
            ucc-gen package --path apps/$ch -o dist/
          done
      - name: Upload to S3
        continue-on-error: true
        uses: shallwefootball/upload-s3-action@master
        env:
          BASE_DIR : "apps"
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: 'philips-ci-test'
          source_dir: 'dist'
          destination_dir: 'apps'
