name: Package Private Apps (Tar)

on: workflow_call

jobs:
  package-and-upload:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ["uat/ses", "uat/es", "prod/es", "prod/ses"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Package Splunk App
        run: |
          ROOT=$(pwd)
          # Find the first-level directory with changes
          CHANGED_FOLDER=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -oE '^enviroments/${{ matrix.environment }}[^/]+' | sort -u | head -n 1)
          if [ -z "$CHANGED_FOLDER" ]; then
            echo "No changes detected in app folders. Exiting."
            exit 1
          fi
          echo "Changed folder: $CHANGED_FOLDER"
          mkdir -p $ROOT/dist
          # Packaging all changed apps
          for ch in $CHANGED_FOLDER
          do
            version=$(cat $ch/app.manifest | jq -r '.info.id.name')
            tar -czf $ROOT/dist/$ch_$version.tar.gz ./$ch
          done
      - name: Upload to S3
        uses: shallwefootball/upload-s3-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: 'philips-ci-test'
          source_dir: 'dist'
          destination_dir: 'apps'
