name: Package Private Apps

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    path:
      - apps/**
  push:
    branches:
      - main
    path:
      - apps/**
  workflow_dispatch:

jobs:
  check-changes-to-apps:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      changed_folders: ${{ steps.check-changes.outputs.changed_folders }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
        # TODO change branch ref
      - name: Check if app folder was modified
        id: check-changes
        run: |
          # Base directory to search
          BASE_DIR="apps"

          # Get the list of modified files in the specified directory
          if [ "$(git rev-list --count HEAD)" -eq 1 ]; then
            git ls-files $BASE_DIR | sed -E 's|/[^/]+$||' | sort -u
            CHANGED_FOLDERS=""
          else
            CHANGED_FOLDERS=$(git diff --name-only HEAD^ HEAD -- $BASE_DIR \
            | sed -E 's|/[^/]+$||' | sort -u)
          fi

          CHANGED_FOLDERS=$(echo "$CHANGED_FOLDERS" | tr '\n' ',' | sed 's/,$//')
          
          if [ -z "$CHANGED_FOLDERS" ]; then
            echo "No folders were modified."
            echo "changed_folders=" >> $GITHUB_OUTPUT
          else
            echo "Modified folders: $CHANGED_FOLDERS"
            echo "changed_folders=$CHANGED_FOLDERS" >> $GITHUB_OUTPUT
          fi
  package-and-upload:
    # if: github.event.pull_request.merged == true
    needs: check-changes-to-apps
    if: needs.check-changes-to-apps.outputs.changed_folders != ''
    runs-on: ubuntu-latest
    services:
      splunk:
        image: splunk/splunk:9.1.3
        env:
          SPLUNK_START_ARGS: --answer-yes --no-prompt --accept-license
          SPLUNK_PASSWORD: password
        options: >-
          --health-interval 30s
          --health-timeout 5s
          --health-retries 5
          --name splunk
        ports:
          - 8000:8000
          - 8089:8089
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
        # TODO change branch ref
      - name: Package Splunk App
        run: |
          ROOT=$(pwd)
          BASE_DIR="apps"
          echo "Changed folders: $CHANGED_FOLDERS"
          dirs=($(echo "$CHANGED_FOLDERS" | awk -F'/' '{if (NF >= 2) print $2}' | sort -u))
          mkdir -p $ROOT/dist
          # Packaging all changed apps
          for ch in "${dirs[@]}"
          do
            # Copy app to docker
            docker cp $BASE_DIR/$ch ${{ job.services.splunk.id }}:/opt/splunk/etc/apps/$ch
            # Package app leveraging Splunk REST API
            # - default/ content will be automatically merged with local/
            path=$(curl -k -u admin:password https://localhost:8089/services/apps/local/$ch/package?output_mode=json | jq -r '.entry | .[].content.path')

            echo "Downloading App $path"
            docker cp ${{ job.services.splunk.id }}:$path $ROOT/dist/

            cd $ROOT/dist
            echo "Changing app extension spl -> tgz"
            file_name=$(ls *.spl | xargs -I"{}" basename {} .spl)

            mv $file_name.spl $file_name.tgz
            cd $ROOT
          done
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 sync ./dist s3://philips-ci-test/apps/
