# this add-on is powered by splunk Add-on builder
[install]
state_change_requires_restart = false
is_configured = 0
state = enabled
build = 1

[launcher]
author = Splunk Inc.
version = 1.0.0

[ui]
is_visible = 0
label = app2

[package]
id = app2


